# 포트 설정
server:
  port: 8083

# JWT 설정
jwt:
  jwtSecret: "aVeryLongSecretKeyThatIsAtLeast32BytesLongForSecurity"
  jwtExpiration: 3600000 # 1시간 (밀리초 단위)

# 스프링 설정
spring:
  # 애플리케이션 이름 설정
  application:
    name: social-graph-service

  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/social_graph_db
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    database: POSTGRESQL
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    # show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
        highlight_sql: true

  # 레디스 설정
  data:
    redis:
      host: localhost
      port: 6379
      password: redis

  # 카프카 설정
  kafka:
    consumer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
      group-id: social-graph-group
    producer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

# msa 로깅 설정 (jaeger)
otel:
  resource:
    attributes:
      service.name: ${spring.application.name}

tracing:
  url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

# gRPC 서버 설정
grpc:
  server:
    port: 50053